name: Windows - RustDesk

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      - name: Download RustDesk
        shell: powershell
        run: |
          Write-Host "Downloading RustDesk..."

          Invoke-WebRequest `
            -Uri "https://github.com/rustdesk/rustdesk/releases/download/1.4.9/rustdesk-1.4.9-x86_64.exe" `
            -OutFile "$env:TEMP\rustdesk.exe"

          Write-Host "Download complete."

      - name: Start RustDesk
        shell: powershell
        run: |
          $rustdesk = "$env:TEMP\rustdesk.exe"

          Write-Host "Starting RustDesk portable..."

          Start-Process $rustdesk
          Start-Sleep -Seconds 15

          & $rustdesk --password "Malek2026RD" | Out-String
          Start-Sleep -Seconds 5

          $id = (& $rustdesk --get-id | Out-String).Trim()

          Write-Host ""
          Write-Host "==============================="
          Write-Host "RUSTDESK READY"
          Write-Host "ID: $id"
          Write-Host "PASSWORD: Malek2026RD"
          Write-Host "==============================="
          Write-Host ""

      - name: Time Counter
        shell: powershell
        run: |
          while ($true) {
            Write-Host "$(Get-Date) - Runner Online"
            Start-Sleep -Seconds 60
          }
