name: Windows - RustDesk

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      - name: Downloading & Installing Essentials
        shell: cmd
        run: |
          curl.exe -L -o login.py "https://www.dropbox.com/scl/fi/az5jzhpuiylnw7yqw9du5/login.py?rlkey=1qjxif8fu35dh0v77nagv2ihh&dl=1"
          curl.exe -L -o loop.bat "https://www.dropbox.com/scl/fi/vji7ekyslpbovokpqeay3/loop.bat?rlkey=876nfzm3qdmyqhc1jckgqjcld&dl=1"
          curl.exe -L -o show.bat "https://www.dropbox.com/scl/fi/cwbwdo2n3tt8rbqmugc6h/show.bat?rlkey=41m0ds12mg6e28giib3zqlf6w&dl=1"
          curl.exe -L -o time.py "https://www.dropbox.com/scl/fi/ox42qglbf6fsnm9erf8cw/timelimit.py?rlkey=opyeqgum1k95kud81xlc7d66r&dl=1"

          curl.exe -L -o rustdesk.exe "https://github.com/rustdesk/rustdesk/releases/download/1.2.1/rustdesk-1.2.1-x86_64.exe"

          python -m pip install pyautogui psutil --quiet

          start "" rustdesk.exe
          timeout /t 10 /nobreak

          python login.py
          timeout /t 10 /nobreak

      - name: Log In To RustDesk
        shell: cmd
        run: |
          call show.bat

      - name: Time Counter
        shell: cmd
        run: |
          python time.py
